DROP TABLE IF EXISTS VETERINARIOS;

CREATE TABLE VETERINARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NRO_LICENCIA VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    ESPECIALIDAD VARCHAR(50) NOT NULL
);

INSERT INTO VETERINARIOS (ID, NRO_LICENCIA, NOMBRE, APELLIDO, ESPECIALIDAD)
VALUES (DEFAULT, 'AE700OP', 'CRISTIAN', 'CRISTALDO', 'CIRUJANO');
